# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.11012135, 0.54310323, 0.72706141],
       [0.70768161, 0.56880194, 0.57634643],
       [0.70004104, 0.37875412, 0.35245623],
       [0.81693687, 0.59521192, 0.6732573 ],
       [0.6729321 , 0.81534376, 0.65093349],
       [0.86265678, 0.75195461, 0.83484891],
       [0.7068635 , 0.22560924, 0.32596513],
       [0.98453827, 0.02594154, 0.97294518],
       [0.92417695, 0.62152227, 0.43526854],
       [0.57509899, 0.10597711, 0.28134898],
       [0.6674127 , 0.33655663, 0.10408534],
       [0.5628289 , 0.62190202, 0.30204604],
       [0.89124535, 0.246514  , 0.91416677],
       [0.39209868, 0.7188402 , 0.38984099],
       [0.539543  , 0.00557969, 0.92051851],
       [0.43550068, 0.11298263, 0.63664777],
       [0.14094073, 0.06127514, 0.98541132],
       [0.79880946, 0.93042524, 0.47264011],
       [0.47964084, 0.14665256, 0.82791016],
       [0.67892155, 0.39888876, 0.92437134],
       [0.6262285 , 0.22571138, 0.08793747],
       [0.07524813, 0.28582146, 0.97140231],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.72661771, 0.03138781, 0.12441775],
       [0.97589286, 0.13418169, 0.32895798]])

In [4]:
from scipy.cluster.vq import vq

In [6]:
#Clusters y distancia al centroide del cluster
vq(data,clust_centers)

(array([0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0]),
 array([1.00254666, 0.56747959, 0.36940773, 0.59695721, 0.81205617,
        0.80646849, 0.28059497, 0.65307748, 0.50147513, 0.23054045,
        0.31152311, 0.63803262, 0.60187464, 0.80928566, 0.7462463 ,
        0.59479949, 1.04173927, 0.82825532, 0.70382872, 0.7160858 ,
        0.22174412, 1.09836317, 0.        , 0.25818902, 1.0357054 ,
        0.83381818, 0.        , 1.09873373, 0.35541963, 0.99289528]))

In [7]:
from scipy.cluster.vq import kmeans

In [8]:
kmeans(data,clust_centers)

(array([[0.48437822, 0.28578629, 0.48113143],
        [0.77537213, 0.59967385, 0.72652973]]),
 0.39795427274190165)

In [10]:
kmeans(data,2)

(array([[0.43425684, 0.20324443, 0.86662318],
        [0.66948556, 0.49969538, 0.42335462]]),
 0.3852826451544785)